In [2]:
import numpy as np

In [3]:
test_matrix =[[4,4,5,6],[3,4,5,8]]
np.array(test_matrix).shape

(2, 4)

In [4]:
np.array(test_matrix).reshape(8,)

array([4, 4, 5, 6, 3, 4, 5, 8])

In [5]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [6]:
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [7]:
np.array(test_matrix).reshape(2,2,2)

array([[[4, 4],
        [5, 6]],

       [[3, 4],
        [5, 8]]])

In [8]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

In [9]:
test_matrix

[[4, 4, 5, 6], [3, 4, 5, 8]]

In [11]:
# 다차원 array를 1차원 array로 변환
np.array(test_matrix).flatten()

array([4, 4, 5, 6, 3, 4, 5, 8])