In [3]:
import numpy as np

### index

In [6]:
test_example = np.array([[1,2,3],[4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
test_example[0][0]

1

In [8]:
test_example[0,0]

1

In [9]:
test_example[0][0] = 10
test_example

array([[10,  2,  3],
       [ 4,  5,  6]])

### slicing

In [12]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [13]:
a[1,1:3]

array([7, 8])

In [14]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [16]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
a[:,::2] #시작점, 끝점, step

array([[ 1,  3,  5],
       [ 6,  8, 10]])