In [5]:
import numpy as np

In [6]:
test_a = np.array([[1,2,3],[4,5,6]],float)

## Element-wise operations

#### Array간 shape이 같을 때 일어나는 연산

In [7]:
test_a + test_a

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [8]:
test_a - test_a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [10]:
test_a *test_a  #같은 위치끼리 곱해준다

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [11]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [12]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [15]:
print(test_a)
print(test_a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## broadcdasting

#### shape이 다른 배열 간 연산을 지원하는 기능 
#### "자동"
어느 정도 shape이 같아야함
ex) 행이면 행, 열이면 열

In [16]:
test_matrix = np.array([[1,2,3],[4,5,6]],float)
scalar = 3

In [18]:
test_matrix + scalar

array([[ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [19]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [20]:
test_matrix * scalar

array([[  3.,   6.,   9.],
       [ 12.,  15.,  18.]])

In [21]:
test_matrix / scalar #나눗셈

array([[ 0.33333333,  0.66666667,  1.        ],
       [ 1.33333333,  1.66666667,  2.        ]])

In [22]:
test_matrix // scalar #몫

array([[ 0.,  0.,  1.],
       [ 1.,  1.,  2.]])

In [23]:
test_matrix ** scalar

array([[   1.,    8.,   27.],
       [  64.,  125.,  216.]])

In [24]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [29]:
def scalar_vector_product(scalar, vector):
    result =[]
    for value in vector:
        result.append(scalar * value)
    return result

iteration_max = 1000000

vector = list(range(iteration_max))
scalar = 2


# timeit: jupyter 환경에서 코드의 퍼포먼스를 체크하는 함수
%timeit scalar_vector_product(scalar, vector) # for loop을 이용한 성능
%timeit [scalar * value for value in range(iteration_max)] #list comprehension을 이용한 선으
%timeit np.arange(iteration_max) * scalar # numpy를 이용한 성능

1 loop, best of 3: 177 ms per loop
10 loops, best of 3: 147 ms per loop
100 loops, best of 3: 4.46 ms per loop


왜 numpy가 list보다 빠른가
앞서 배웠던 것처럼
list는 저장소를 따로 두고  찾아가는 구조이고
numpy는 그대로 쌓아올려서 따로 안돌아다녀도 되서 
계산시간이 numpy < list이다.