In [2]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [7]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [8]:
sum(a<10)

10

In [4]:
np.any(a>5) ,  np.any(a<0)

(True, False)

In [5]:
np.all(a>5), np.all( a<10)

(False, True)

In [ ]:
#comparsion operation #1

In [9]:
test_a = np.array([1,3,0],float)
test_b = np.array([5,2,1],float)
test_a > test_b

array([False,  True, False], dtype=bool)

In [11]:
test_a == test_b

array([False, False, False], dtype=bool)

In [12]:
(test_a > test_b).any()

True

In [14]:
#comparsion operation #2

a = np.array([1,3,0],float)
np.logical_and (a>0, a<3) # and조건의 condition

array([ True, False, False], dtype=bool)

In [15]:
b = np.array([True,False, True],bool)
np.logical_not(b)

array([False,  True, False], dtype=bool)

In [17]:
c = np.array([False, True, False], bool)
np.logical_or(b,c)

array([ True,  True,  True], dtype=bool)

In [20]:
# where (condition, True, False)
# 엑셀이랑 같음
print(a)
np.where(a>0,3,2) 

[ 1.  3.  0.]


array([3, 3, 2])

In [21]:
a = np.arange(5,15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.where(a>10)

(array([6, 7, 8, 9], dtype=int64),)

In [23]:
a = np.array([1,np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False], dtype=bool)

In [25]:
np.isfinite(a)

array([ True, False, False], dtype=bool)

In [26]:
a = np.array([1,2,3,4,5,6,7,8])
np.argmax(a), np.argmin(a) #index반환

(7, 0)

In [28]:
# 최댓값, 최소값
a = np.array([[1,2,4,7],[9,64,3,86],[4,7,99,1]])
np.argmax(a, axis=1), np.argmin(a, axis=0)
 # axis =1 : row
# axis =2 :  cloumn

(array([3, 3, 2], dtype=int64), array([0, 0, 1, 2], dtype=int64))