In [1]:
import numpy as np

## Boolean

In [2]:
test_array = np.array([1,4,3,6,8,9], float)
test_array >3

array([False,  True, False,  True,  True,  True], dtype=bool)

In [3]:
test_array[test_array>3]

array([ 4.,  6.,  8.,  9.])

In [4]:
condition = test_array <3
test_array[condition]

array([ 1.])

## Fancy

In [5]:
a = np.array([2,4,6,8],float)
b = np.array([0,0,1,2,1,0], int) 
a[b] # bracket index, b배열의 값을 index로 하여 a의 값들을 추출함

array([ 2.,  2.,  4.,  6.,  4.,  2.])

In [6]:
#이걸 더 권장
a.take(b) #take함수 : bracket index와 같은 효과

array([ 2.,  2.,  4.,  6.,  4.,  2.])

In [7]:
a = np.array([[1,4],[9,16]],float)
b = np.array([0,0,1,1,0],int)
c = np.array([1,0,1,0,1],int)
a[b,c]

array([  4.,   1.,  16.,   9.,   4.])