In [1]:
import numpy as np

In [3]:
test_array = np.array([1,4,5,7],float) # np.array => ndarray
print(test_array)
type(test_array[3])

# list와 가장 큰 차이점 :  Dynamic typing not supported (속도를 잃음)
# BUT C의 Array를 사용하여 배열을 생성함(속도를 지킴)

[ 1.  4.  5.  7.]


numpy.float64

In [5]:
test_array = np.array([1,4,5,"7"],float)
print(test_array)
type(test_array[3])

[ 1.  4.  5.  7.]


numpy.float64

In [6]:
test_array.dtype

dtype('float64')

In [7]:
test_array

array([ 1.,  4.,  5.,  7.])

In [8]:
test_array.shape

(4,)

In [9]:
np.array(test_array, int).ndim #몇차원인지

1

In [10]:
np.array([[1,2,3],[4.5, "5", "6"]], dtype=np.float32).nbytes
#32bits = 4bytes -> 6*4bytes

24

In [11]:
np.array([[1,2,3],[4.5, "5", "6"]], dtype=np.int8).nbytes
#8bits = 1 bytes -> 6*1bytes

6

In [13]:
np.array([[1,2,3],[4.5, "5", "6"]], dtype=np.float64).nbytes
#64bits = 8bytes -> 6*8bytes

48